name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy to AWS EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Navigating to project directory"
            cd demo-springboot-cicd
            
            echo "Pulling latest changes..."
            git pull || exit
            
            echo "Restarting application using PM2..."
            pm2 restart demo-cicd